### ISSUE TITLE
disallow 0b10000000, negative 4-bit integer with zero magnitude

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/superpack-spec#1]
It's equivalent to `0b00000000`, non-negative 6-bit integer with zero magnitude.

**Comment by sanscore** [comment]
Spec-wise, is there potential for negative impact? 

The only way that I know to mitigate the problem, from the spec, would be to redefine `nint`s as twos-complements; instead of signed-magnitude.

Implementation-wise, sure. There may be issues dependent on the language and conversion technique. If that's the concern behind this issue, then add a new section to the precautions section because there will need to safety guards from reading

Assume  there's an implementation bug in `GrantsSuperTerribleEncoder`, that encodes not just negative-zero for `nint4`, but negative-zero  for `nint8`, `nint16`, `nint32`, and `nint64` as well. If I pass my encoded file over to you, and you decode it with your `MichaelsSuperOptimizedDecoder`, which may cause some _implementation-undefined_ issue because I supplied you bad data.

**Comment by michaelficarra** [comment]
We can literally just unreserve that specific byte in the specification. Not a problem.

I'd like to add, the reason this is important is that we'd like two compliant encoders to produce the same output given the same input. Currently they will arbitrarily make the choice to encode the integer zero as either 0x80 or 0x00.

**edit:** Oh, I forgot to address the latter concern. Yes, I think we should eliminate the other ways to encode zero in the various nint\* spaces.

**edit again:** Ah crap, there's the whole overlap of those spaces. Forget what I've said. I need to think more about the motivation behind this change again.

**Comment by michaelficarra** [comment]
Oh, I forgot to address the latter concern. Yes, I think we should eliminate the other ways to encode zero in the various nint* spaces.

**Comment by sanscore** [comment]
The more I think about twos-complement, the more I'm unsure about it. It seems like a good solution to this problem, but then I think about how I might implement SuperPack in C (which I won't be doing, except as a mental exercise).

## Hypothetical C implementation

### Ambiguous Struct

In C, to be memory space efficient. If I were to encounter a `nint` as it is defined (`0..-15`), then I could choose to make a struct that stores in the comparable `unsigned uintN_t` and a "boolean"(`_Bool`; char) to signal if it is a negative or positive value. 
- As is, this would work great.
  - Though interacting with the struct may be odd. `sp_int.sign ? -1 * sp_int.value : sp_int.value`
- If `nint`s were twos complement, then there would be underflow issues representing `INTN_MIN`; ex: `-65536` cannot be stored as an `uint16_t.

### Double-sized Signed Type

An alternative way to do something similar would to be to store values in the signed `intNN_t` of the Superpack type; i.e. int16_t > int32_t, int32_t > int64_t.
- As is, then we lose the full potential by 1; `INTN_MIN - 1`.
- If `nint`s were twos complement, then it would fit neatly.

However, this is doubling the space efficiency.

### Lazy, Convient Method

Ultimately, I would just use `int64_t` for all integer values because it's the lazy thing to do. Plus, memory is cheap, so who cares.

I'm realizing now that this _long_ comment may not be productive to the conversation, but I can't not submit it now.

## Overlap Issue

You mentioned the overlap problem exists in `nint`. It exists in `uint`s as well, but I expect taht overlap is more of a non-issue.

**Comment by michaelficarra** [comment]
Okay, I think this overlap/nondeterminism issue can be solved by mandating that each integer must be encoded using the smallest encoding available and, in the case of a tie (which I believe only happens for the case mentioned in the OP), defining some secondary ordering.

We would still have to consider your point about decoders needing to use the appropriate size integer; presumably the same size as the one they encoded. I'll continue thinking about it.

**Comment by LewisJEllis** [comment]
@michaelficarra should the spec be updated to follow the implementation change made in shapesecurity/superpack-js#31?

**Comment by michaelficarra** [comment]
@LewisJEllis I think so, yes. As part of closing this issue, we should also mandate that all `-0` values are encoded as a float.

**Comment by michaelficarra** [comment]
Done in #10.
